Fix languages package build error
The latest patch was rebased and merged using Github, and therefore was
not tested in its final form.  Unfortunately, it broke due to some more
recent changes.

[compile] src/node/language-server-contribution.ts(112,44): error TS2345: Argument of type 'ProcessErrorEvent' is not assignable to parameter of type 'Error'.

This patch fixes it.

Change-Id: Ic905fdd07078f129177284e17582d5698e67e4ac
Signed-off-by: Simon Marchi <simon.marchi@ericsson.com>