[browser tests] [browser-utils] [find-replace] increase testsuites timeout
These test suites executes early, a the same time plugins are started. The default 2000ms
timeout would occasionally seemingly not be enough. Increasing it a bit.

e.g.:
2023-02-17T20:28:21.717Z root INFO   1 failing
2023-02-17T20:28:21.719Z root INFO   1) animationFrame
       should resolve after the given number of frames:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

2023-02-20T14:54:45.051Z root INFO   1 failing
2023-02-20T14:54:45.051Z root INFO   1) Find and Replace
       "after each" hook for "Replace in the active explorer with the current editor":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

Signed-off-by: Marc Dumais <marc.dumais@ericsson.com>